# Dockerfile.product_tracker_bot
# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy project files into the container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r main_requirements.txt

# Command to run the application
CMD ["python", "main.py"]