version: "3.9"
services:
  product-tracker-bot:
    build:
      context: .
      dockerfile: Dockerfile.product_tracker_bot
    container_name: product_tracker_bot
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///data/prices.db
    restart: unless-stopped

  webhook-service:
    build:
      context: .
      dockerfile: Dockerfile.webhook_service
    container_name: webhook_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///data/prices.db
    restart: unless-stopped